routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Auth::routes();
Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('posts', 'PostsController');
    Route::resource('comments', 'CommentsController');
});

app/Post.php
<?php


namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Post extends Model
{
    use SoftDeletes;

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'title',
        'cover_image',
        'created_at',
        'updated_at',
        'description',
        'author',
        'deleted_at',
    ];
}

app/PostComment.php
<?php


namespace App;


use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class PostComment extends Model
{
    use SoftDeletes;

    protected $table = 'posts_comments';

    protected $fillable = [
        'id',
        'username',
        'post_id',
        'body',
        'created_at',
        'updated_at',
        'deleted_at',
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/CommentsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Post;
use App\PostComment;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class CommentsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       $comments = PostComment ::all();

        return view('posts.index', compact('comments'));
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('comments.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try{
            $user = Auth::user();
            $commentByUser = PostComment::create([
                'post_id' => $request->post,
                'username' =>$user->name,
                'body' => $request->body
            ]);

            return  redirect()->back()->with('message', 'Comment saved successfully!');
        }
        catch (\Exception $e) {
            return  redirect()->back()->with('message', $e->getMessage());
        }
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Post;
use App\PostComment;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class PostsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       $posts = Post ::all();

        return view('posts.index', compact('posts'));
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('posts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try{
            $this->validate($request, [
                'title' => 'required',
                'cover_image' => 'image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            ]);

            if ($request->hasFile('image')) {
                $image = $request->file('image');
                $name =  url('/images').'/'.time().'.'.$image->getClientOriginalExtension();
                $destinationPath = public_path('/images');
                $image->move($destinationPath, $name);
            }
            else {
                $name = 'noimage.png';
            }
            $request->request->add(['cover_image' => $name]);

            $posts = Post::create($request->all());

            return  redirect()->back()->with('message', 'Post saved successfully!');
        }
        catch (\Exception $e) {
            return  redirect()->back()->with('message', $e->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $post = Post::find($id);
        $postComments = DB::table('posts_comments')
            ->select ('*')
            ->where('post_id', $post->id)
            ->get();

        return view('posts.show', compact('post','postComments'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $posts = Post::find($id);

        return view('posts.edit', compact('posts'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post)
    {
        try {
            $validator = \Illuminate\Support\Facades\Validator::make($request->all(), [
                'image' => 'image|mimes:jpeg,png,jpg,gif,svg|max:2048',
                'title' => 'required',
            ]);

            if ($request->hasFile('image')) {
                $image = $request->file('image');
                $name = url('/images') . '/' . time() . '.' . $image->getClientOriginalExtension();
                $destinationPath = public_path('/images');
                $image->move($destinationPath, $name);
            } else {
                $name = $post->cover_image;
            }
            $request->request->add(['cover_image' => $name]);

            $post->update($request->all());

            return  redirect()->back()->with('message', 'Post updated successfully!');

        }
        catch (\Exception $e) {
            return  redirect()->back()->with('message', $e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $posts = Post::find($id);
            $posts->delete();

            return  redirect()->back()->with('message', 'Post deleted successfully!');
        }
        catch (\Exception $e) {
            return  redirect()->back()->with('message', $e->getMessage());
        }
    }
}

resources/views/base.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Posts</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>
<body>
<div class="container">
    @yield('main')
</div>
</body>
</html>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in! Please open <a href="/posts"> posts here</a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/posts/create.blade.php
@extends('base')

@section('main')
    <div class="row">
        <div class="col-sm-8 offset-sm-2">
            <h1 class="display-6">Add a post</h1>
            <div>
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div><br />
                @endif
                    <form action="{{ route("posts.store") }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        @if (session()->has('message'))
                            <div class="alert alert-info">
                                {{ session('message') }}
                            </div>
                        @endif
                        <div class="form-group">
                            <label for="title">Post Title*</label>
                            <input type="text" id="title" name="title" class="form-control" required>

                        </div>
                        <div class="form-group">
                            <label for="description">Description</label>
                            <textarea class="form-control" name="description" rows="5" cols="20"></textarea>
                        </div>
                        <div class="form-group">
                            <label for="cover_img">Cover Image</label>
                            <input type="file" id="image" name="image" class="form-control">
                        </div>
                        <div>
                            <input class="btn btn-primary" type="submit" value="Save">
                        </div><br>
                        <a class="btn btn-xs btn-info" href="{{ route('posts.index') }}">
                            Go Back
                        </a>
                    </form>
            </div>
        </div>
    </div>
@endsection

resources/views/posts/edit.blade.php
@extends('base')

@section('main')
    <div class="row">
        <div class="col-sm-8 offset-sm-2">
            <h1 class="display-6">Edit post</h1>
            <div>
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div><br />
                @endif
                    <form action="{{ route("posts.update", [$posts->id]) }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                    @if (session()->has('message'))
                        <div class="alert alert-info">
                            {{ session('message') }}
                        </div>
                    @endif
                    <div class="form-group">
                        <label for="title">Post Title*</label>
                        <input type="text" id="title" name="title" class="form-control" value="{{ old('title', isset($posts) ? $posts->title : '') }}" required>

                    </div>
                    <div class="form-group">
                        <label for="description">Description</label><br>
                        <textarea class="form-control" name="description" rows="5" cols="20">{{ old('description', isset($posts) ? $posts->description : '') }}</textarea>
                    </div>
                    <div class="form-group">
                        <label for="cover_img">Cover Image</label><br>
                        <img src="{{ $posts->cover_image }}"  width="200" height="150" class="rounded">
                        <input type="file" id="image" name="image" class="form-control" value="{{ old('cover_image', isset($posts) ? $posts->cover_image : '') }}">
                    </div>
                    <div>
                        <input class="btn btn-primary" type="submit" value="Update">
                    </div><br>
                    <a class="btn btn-xs btn-info" href="{{ route('posts.index') }}">
                        Go Back
                    </a>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/posts/index.blade.php
@extends('base')

@section('main')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route("posts.create") }}">
                Add Post
            </a>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <h1 class="display-6">Posts</h1>
            <table class=" table table-bordered table-striped table-hover datatable" id="example">
                <thead>
                <tr>
                    <th width="10">
                        Nr
                    </th>
                    <th>
                        Title
                    </th>
                    <th>
                        Description
                    </th>
                    <th>
                        Cover image
                    </th>

                    <th>
                        Actions   &nbsp;
                    </th>
                </tr>
                </thead>
                <tbody>
                <?php $i = 0 ?>
                @foreach($posts as $key => $post)
                    <?php $i++ ?>
                    <tr data-entry-id="{{ $post->id }}">
                        <td>
                            {{$i}}
                        </td>
                        <td>
                            {{ $post->title ?? '' }}
                        </td>
                        <td>
                            {{ $post->description ?? '' }}
                        </td>
                        <td>
                            <img src="{{ $post->cover_image}}"  style="width:90%" align="center" class="rounded" >
                        </td>
                        <td>
                            <a class="btn btn-xs btn-primary" href="{{ route('posts.show', $post->id) }}">
                               View
                            </a>

                            <a class="btn btn-xs btn-warning" href="{{ route('posts.edit', $post->id) }}">
                                Edit
                            </a>

                            <form action="{{ route('posts.destroy', $post->id)}}" method="post">
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-danger" type="submit">Delete</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
            <div>
            </div>
@endsection

resources/views/posts/show.blade.php
@extends('base')

@section('main')
    <style type="text/css">
        .post {
            color: #464646;
            font-family: 'proxima-nova', Helvetica, Arial, sans-serif;
            font-size: 14px;
            line-height: 1.5em;
            background: #f0f0f0;
            padding: .75rem 1.25rem;
        }
        .post-title{
            margin: 3px 0 10px 0;
            min-height: 0px;
            font-weight: 700;
            font-size: 28px;
            line-height: 36px;
        }

        .singlepostinfo{
            font-size: 15px;
            color: #999;
            margin: 0 0 15px;
        }
        .post-content p{
            font-size: 15px;
            line-height: 1.8em;
        }
        .comment{
            background:#fff !important;
            color:#999;
            width: 500px;
            height: 100px;
            font-family: 'proxima-nova', Arial,Tahoma,Verdana;
            font-size:15px;
            padding: 10px 10px;
            margin:5px 0 5px 10px;
            border:1px solid #dfdfdf;
            outline: none;
        }
        .comment-header{
            font-family: "Proxima Nova" , 'proxima-nova', Arial, Helvetica, sans-serif;
            font-size: 17px;
            display: inline-block;
            margin: 20px 0 0;
            margin-left: 10px;
            color: #464646;
        }
    </style>
    <div class="card">
        <h2 class="card-header">
            Post Details
        </h2>

        <div class="post">

            <div class="post-header">
                <h1 class="post-title"> {{ $post->title }}</h1>
            </div>
            <div class="singlepostinfo">
                Last updated on {{ $post->updated_at }} </div>
            <div class="post-content">
                <p>
                    <img src="{{ $post->cover_image}}" width="300" class="rounded" >
                </p>
                <p>
                    {!! $post->description !!}
                </p>
            </div>
        </div><br>
        <a class="btn btn-xs btn-warning" style="margin-bottom: 10px" href="#">
            Leave a reply
        </a>
        <div class="row">
            <div class="col-sm-4 offset-sm-2" style="margin-left: 10px">

                    <form action="{{ route("comments.store") }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        @if (session()->has('message'))
                            <div class="alert alert-info">
                                {{ session('message') }}
                            </div>
                        @endif
                        <input type="hidden"  name="post" value= "{{ $post->id }}">

                        <div class="form-group">
                            <textarea class="form-control" name="body" rows="5" cols="20" placeholder="Your comment" required></textarea>
                        </div>
                        <div>
                            <input class="btn btn-primary" type="submit" value="Submit comment">
                        </div>
                    </form>
                </div>
            </div>

            @foreach($postComments as $key => $comments)
                <div class="comment-header">
                    <b>{{ $comments->username ?? '' }} </b>
                    <br>
                     {{ $comments->created_at ?? '' }}
                </div>
                <div class = "comment">
                     {{ $comments->body ?? '' }}
                </div>
            @endforeach
        </div>
    </div>

@endsection